apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jenkins
  namespace: {{ .Values.route.namespace }}
  labels:
    app: jenkins
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: jenkins
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
