apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: devops
  labels:
    app: jenkins
type: Opaque
data:
  username: YWRtaW4=  # Base64-encoded 'admin'
  password: YWRtaW5AMTIz  # Base64-encoded 'admin@123'

