replicaCount: 1
image:
  repository: "registry.redhat.io/ocp-tools-4/jenkins-rhel8"
  tag: ""
  digest: "sha256:e7bf834b4817ac7f88129711f2ce833d338676d6fae5efd12683ed885bd9fc8b"
  pullPolicy: "IfNotPresent"
route:
  enabled: true
  name: Jenkins-dr
  host: jenkins.apps.ocp-prod-main.internal.eg.vodafone.com
  namespace: devops

secrets:
  jenkins:
    name: jenkins-secret
    username: username
    password: password

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "ocs-storagecluster-cephfs"

service:
  port: 80
  targetPort: 8080

serviceAccount:
  create: false
  name: "" # Leave empty to use the default ServiceAccount

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

# Jenkins specific section for overriding initial admin credentials
jenkins:
  Master:
    adminUser: ""
    adminPassword: ""
#  openShift:
 #   enableOAuth: false
